name: Deploy Statmic site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Bump PHP version
        id: cache-apt
        run: "sudo apt install software-properties-common && sudo add-apt-repository ppa:ondrej/php && sudo apt update && sudo apt install php8.3 php-curl"
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build Vite
        run: npm run build
      - name: Deploy to Cloudways server
        uses: dchymko/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "./public_html"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER_REQUIRED: true
          SCRIPT_AFTER: |
            cd public_html
            whoami
            ls -al
            export NPM_CONFIG_CACHE=~/public_html
            npm run build
            composer update
